DROP TABLE events;

CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  lvl TEXT CHECK (lvl IN ('high', 'middle')),
  title TEXT NOT NULL,
  descr TEXT NOT NULL,
  test BOOLEAN NOT NULL DEFAULT FALSE,
  submission BOOLEAN NOT NULL DEFAULT FALSE,
  deadline TEXT,
  rubric TEXT NOT NULL
);

CREATE TABLE event_themes (
  id SERIAL PRIMARY KEY,
  event_id SERIAL,
  theme TEXT NOT NULL,
  FOREIGN KEY (event_id) REFERENCES events(id)
);

INSERT INTO events (lvl, title, descr, test, submission, deadline, rubric) VALUES
  ('middle', 'Audio Podcasting', 'Participants use digital audio technology to create original content for a podcast piece that addresses the annual theme. The podcast must feature high level storytelling techniques, voice acting, and folly sound effects. The full entry must include documentation of the podcast development process and elements. Semifinalists complete an onsite challenge to produce an additional podcast(s).', FALSE, FALSE, 'None', 'audio-podcasting.pdf'),
  ('middle', 'Biotechnology', 'To address the annual theme, participants select a contemporary biotechnology issue and demonstrate understanding of the topic through their documented research and an original display. Semifinalists participate in an interview.', FALSE, FALSE, 'None', 'biotechnology.pdf'),
  ('middle', 'Career Prep', 'Based on the annual theme, participants conduct research on a technology-related career, prepare a letter of introduction to a potential employer, and develop a job-specific resume. Semifinalists participate in a mock job interview.', FALSE, FALSE, 'None', 'career-prep.pdf'),
  ('middle', 'Challenging Technology Issues', 'Following the onsite random selection of a technology topic from a group of pre-conference posted topics, participants work to prepare for and deliver a debate-style presentation, in which they explain opposing views of the selected topic.', FALSE, FALSE, 'None', 'challenging-technology-issues.pdf'),
  ('middle', 'Chapter Team', 'Participants take a parliamentary procedure test to qualify for the semifinal round of competition. Semifinalists conduct an opening ceremony, items of business, parliamentary actions, and a closing ceremony.', FALSE, FALSE, 'None', 'chapter-team.pdf'),
  ('middle', 'Children''s Stories', 'Participants create an illustrated children''s story based on the annual theme. The entry product is a physical storybook of artistic, instructional, and social value. Semifinalists read their story aloud and participate in an interview.', FALSE, FALSE, 'None', 'childrens-stories.pdf'),
  ('middle', 'Coding', 'To qualify for the semifinal round of competition, participants take a test that concentrates on computer science and coding. Semifinalists demonstrate their programming knowledge by developing a solution to an onsite coding challenge.', FALSE, FALSE, 'None', 'coding.pdf'),
  ('middle', 'Community Service Video', 'Participants create a video that depicts the local TSA chapter''s involvement in a community service project. Semifinalists deliver a presentation on the project and participate in an interview.', FALSE, FALSE, 'None', 'community-service-video.pdf'),
  ('middle', 'Computer Aided Design (CAD) Foundations', 'Participants demonstrate their understanding of CAD fundamentals by creating a two-dimensional (2D) graphic representation of an engineering part or object and answering questions from evaluators about their entry.', FALSE, FALSE, 'None', 'cad-foundations.pdf'),
  ('middle', 'Construction Challenge', 'Participants submit a scale model, display, and documentation portfolio for a design idea and plan for their construction solution based on the annual theme. Semifinalists deliver a presentation about their entry and participate in an interview.', FALSE, FALSE, 'None', 'construction-challenge.pdf'),
  ('middle', 'Cybersecurity', 'Participants take a test that assesses knowledge of cybersecurity vocabulary and the skills needed to execute common cybersecurity tasks. Using digital presentation software, semifinalists deliver a presentation that addresses the annual theme/problem.', FALSE, FALSE, 'None', 'cybersecurity.pdf'),
  ('middle', 'Data Science and Analytics', 'Participants conduct research on the annual topic and analyze the provided data set, document their research in supporting portfolio, and create a display. Semifinalist teams participate in an onsite presentation highlighting their pre-conference submission.', FALSE, FALSE, 'None', 'data-science-and-analytics.pdf'),
  ('middle', 'Digital Photography', 'Participants produce and submit a digital photographic portfolio that relates to the annual theme. Semifinalists participate in an onsite photographic challenge and a presentation/interview.', FALSE, FALSE, 'None', 'digital-photography.pdf'),
  ('middle', 'Dragster', 'Participants design, draw, and construct a CO2-powered dragster that adheres to the annual specifications, design and documentation requirements, and theme. Semifinalists participate in an interview and compete in a double-elimination race.', FALSE, FALSE, 'None', 'dragster.pdf'),
  ('middle', 'Drone Challenge (UAV)', 'Teams study the principles of flight and research the use of drones to address an annual theme. They demonstrate their knowledge of drones in manual flight missions and create a documentation portfolio. Semifinalists participate in an onsite interview.', FALSE, FALSE, 'None', 'drone-challenge.pdf'),
  ('middle', 'Electrical Applications', 'Participants take a test on basic electrical and electronic theory. In response to an onsite challenge, semifinalists assemble a specified circuit from a schematic diagram, make required electrical measurements, and explain their solution in an interview.', FALSE, FALSE, 'None', 'electrical-applications.pdf'),
  ('middle', 'Flight', 'Participants submit a documentation portfolio and fabricate a glider designed to stay in flight for the greatest elapsed time. Semifinalists use their technical drawing skills to construct a glider that is flown onsite.', FALSE, FALSE, 'None', 'flight.pdf'),
  ('middle', 'Forensic Technology', 'Participants take a test of basic forensic science theory to qualify for the semifinal round of competition. Semifinalists participate in an onsite forensic skills demonstration.', FALSE, FALSE, 'None', 'forensic-technology.pdf'),
  ('middle', 'Inventions and Innovations', 'Participants research a need - and brainstorm a solution - for an invention or innovation that can be produced using recycled materials. Participants document their work in an interactive display and create a model/prototype. Semifinalists deliver a presentation about their work and participate in an interview.', FALSE, FALSE, 'None', 'inventions-and-innovations.pdf'),
  ('middle', 'Leadership Strategies', 'Participants prepare for and deliver a presentation about a specific challenge that officers of a TSA chapter might encounter. Semifinalists follow the same competition procedure but must respond to a different chapter challenge.', FALSE, FALSE, 'None', 'leadership-strategies.pdf'),
  ('middle', 'Mass Production', 'Participants manufacture a marketable product that addresses the annual theme. The development of the product prototype is documented in a portfolio that presents participant knowledge and skills related to the mass production process. Through a demonstration of the prototype and an interview, semifinalists support the viability of the prototype.', FALSE, FALSE, 'None', 'mass-production.pdf'),
  ('middle', 'Mechanical Engineering', 'Participants design, document, and build a mechanical device (working catapult) that incorporates the elements of the annual theme/problem. Finalists are determined based on an evaluation of the documentation portfolio and participation in a head-to-head bracket.', FALSE, FALSE, 'None', 'mechanical-engineering.pdf'),
  ('middle', 'Medical Technology', 'Participants conduct research on a contemporary medical technology issue related to the annual theme, document their research, create a display, and build a prototype. Semifinalists deliver a presentation about their entry and participate in an interview.', FALSE, FALSE, 'None', 'medical-technology.pdf'),
  ('middle', 'Microcontroller Design', 'To address the annual theme/problem, participants design and create a working digital device, document the development process, and demonstrate their product as part of a presentation.', FALSE, FALSE, 'None', 'microcontroller-design.pdf'),
  ('middle', 'Off the Grid', 'In response to the annual theme, participants conduct research on a sustainable architectural design for a home in a specified country. They then produce a portfolio and create a display and a model. Semifinalists present their design and participate in an interview.', FALSE, FALSE, 'None', 'off-the-grid.pdf'),
  ('middle', 'Prepared Speech', 'Participants deliver a timed speech that relates to the theme of the current national TSA conference. Semifinalists and finalists are determined using the same competition procedure.', FALSE, FALSE, 'None', 'prepared-speech.pdf'),
  ('middle', 'Problem Solving', 'Participants use problem-solving skills to design and build a solution to an onsite challenge. Solutions are evaluated using measures appropriate to the challenge, such as elapsed time, horizontal or vertical distance, and/or strength.', FALSE, FALSE, 'None', 'problem-solving.pdf'),
  ('middle', 'Promotional Marketing', 'Participants create and submit a marketing portfolio and required elements that address the annual theme/problem. Semifinalists complete a layout and design assignment for evaluation.', FALSE, FALSE, 'None', 'promotional-marketing.pdf'),
  ('middle', 'Robotics', 'Participants design, build, document, and test a robot assembled using open-sourced parts according to stated specifications and to meet the challenge of the yearly theme/problem.', FALSE, FALSE, 'None', 'robotics.pdf'),   
  ('middle', 'Solar Racer', 'Participants apply STEM concepts, creativity, teamwork, and problem-solving skills to design, construct, and race a solar-powered model car. Documentation of the process is required.', FALSE, FALSE, 'None', 'solar-racer.pdf'),
  ('middle', 'STEM Animation', 'Participants design and create a STEM animation video and documentation portfolio to address the annual theme/problem. Semifinalists present their animation and explain the elements of their portfolio/entry.', FALSE, FALSE, 'None', 'stem-animation.pdf'),
  ('middle', 'Structural Engineering', 'Participants apply the principles of structural engineering to design and construct a structure that complies with the annual challenge. An assessment of the required documentation and the destructive testing of the structure (to determine its design efficiency) determine both semifinalists and finalists.', FALSE, FALSE, 'None', 'structural-engineering.pdf'),
  ('middle', 'System Control Technology', 'In response to a challenge presented onsite at the conference, participants analyze a problem (typically one in an industrial setting), build and program a computer-controlled mechanical model to solve the problem, explain the program and the features of the mechanical model solution, and provide instructions for evaluators to operate the device.', FALSE, FALSE, 'None', 'system-control-technology.pdf'),
  ('middle', 'Tech Bowl', 'Participants demonstrate their knowledge of TSA and concepts addressed in technology content standards by completing an objective test. Semifinalists participate in a head-to-head, team competition.', FALSE, FALSE, 'None', 'tech-bowl.pdf'),
  ('middle', 'Technical Design', 'Participants demonstrate their ability to use the technical design process to solve an engineering design problem provided onsite at the conference. Required elements of the entry are presented in a portfolio that includes technical drawings for a minimum of three viable solutions.', FALSE, FALSE, 'None', 'technical-design.pdf'),
  ('middle', 'Video Game Design', 'Participants design, build, provide documentation for, and launch an E-rated, online game on a subject of their choice. Onsite at the conference, semifinalists deliver a presentation and participate in an interview to demonstrate the knowledge and expertise gained during the development of the game.', FALSE, FALSE, 'None', 'video-game-design.pdf'),
  ('middle', 'Website Design', 'To address the annual challenge, participants design, build, provide documentation for, and launch a website that incorporates the elements of website design, graphic layout, and proper coding techniques. Semifinalists participate in an interview to demonstrate the knowledge and expertise gained during the development of the website.', FALSE, FALSE, 'None', 'website-design.pdf');



UPDATE events SET submissions=TRUE, deadline='March 27, 2026' 
 WHERE ((id=42) OR (id=44) OR (id=49) OR (id=54) OR (id=69) OR (id=72) OR (id=77) OR (id=78));